# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1480d07f2602f43f88df5cc55b184b9d290beb8dc3d04c171cdfedf2e7308c3bd0b66e94524191abd56d5a165189f4b34076cdcc19f298d337658da13bef36e9

test:
  secret_key_base: a9186644792b41105364a973070a23b3032f09a25d1515c1ba1d6c11716e7e3d30ddf5eded178be63d27fbf294161aa3a6fff6c20ef9b141bab8543701286526

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
